// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://juamkehykcohwufehqfv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp1YW1rZWh5a2NvaHd1ZmVocWZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3NTY2OTIsImV4cCI6MjA2MjMzMjY5Mn0.jQk-SoPxy9I-r6oWFRtv9dQVvNBRNVUiuYTscN_Pu0k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true
  }
});